//! RFC-001 AC2 property test — trust-tier ceiling.
//!
//! AC2 invariant (from `docs/rfc/0001-identity-layer.md` §Acceptance Criteria):
//!
//!   No combination of identity-claim events — attaching an `op_cert`,
//!   attaching a `member_cert` against an accepted org, receiving a
//!   `pair_drop_ack`, even repeatedly — can raise any peer to
//!   `Tier::Verified` without an explicit, bilateral SAS-confirmation
//!   event for that peer.
//!
//! Implementation note: we drive the actual `wire::trust` state machine
//! through a random walk of model events generated by `proptest`. The
//! events that mutate trust state are deliberately the narrow set that
//! the RFC-001 promotion functions expose (`promote_to_org_verified`,
//! `promote_to_verified`), plus pin/no-op events that should NEVER affect
//! the ceiling. The test is purely about the policy boundary; it does
//! NOT exercise the ed25519 cert primitives (those have their own unit
//! tests in `src/identity.rs`).

use proptest::collection::vec;
use proptest::prelude::*;
use serde_json::Value;
use std::collections::HashSet;
use wire::agent_card::{build_agent_card, sign_agent_card};
use wire::signing::generate_keypair;
use wire::trust::{
    Trust, add_agent_card_pin, empty_trust, get_tier, promote_to_org_verified, promote_to_verified,
};

const PEERS: &[&str] = &["alice", "bob", "carol", "dave"];

/// Model events. We deliberately enumerate the inputs the policy layer
/// reacts to — cryptographic primitives are out of scope here.
#[derive(Clone, Debug)]
enum Event {
    /// Pin the peer's signed card at UNTRUSTED. Idempotent in our model
    /// (re-pin overwrites the entry but never elevates tier on its own).
    AddPin(usize),
    /// Simulate receiving a verified `op_cert` for the peer. Per RFC-001
    /// this updates the agent-card identity claims but DOES NOT mutate
    /// the trust tier — the state machine ignores it. Including this in
    /// the walk proves the ceiling holds even when claim events fire.
    #[allow(dead_code)]
    AttachOpCert(usize),
    /// Simulate the peer's `member_cert` verifying against an org we
    /// accept. Per RFC-001 this triggers `promote_to_org_verified` —
    /// UNTRUSTED → ORG_VERIFIED. Above UNTRUSTED it is rejected and the
    /// tier is unchanged.
    AttachOrgCert(usize),
    /// Simulate inbound `pair_drop_ack`. By itself this is not a SAS
    /// confirmation — it acknowledges receipt of our slot token. The
    /// peer is still UNTRUSTED-or-ORG_VERIFIED until SAS runs.
    #[allow(dead_code)]
    ReceivePairDropAck(usize),
    /// The ONE event that crosses the AC2 ceiling: a successful bilateral
    /// SAS ceremony for `peers[idx]`. This is the event the property test
    /// asks about — we count whether any of these fire for each peer.
    SasConfirmed(usize),
}

fn event_strategy() -> impl Strategy<Value = Event> {
    let idx = 0usize..PEERS.len();
    prop_oneof![
        idx.clone().prop_map(Event::AddPin),
        idx.clone().prop_map(Event::AttachOpCert),
        idx.clone().prop_map(Event::AttachOrgCert),
        idx.clone().prop_map(Event::ReceivePairDropAck),
        idx.prop_map(Event::SasConfirmed),
    ]
}

/// Pin a fresh signed card for `peer_handle` if not already pinned.
fn ensure_pinned(trust: &mut Trust, peer_handle: &str, cards: &mut Vec<(String, Value)>) {
    if cards.iter().any(|(h, _)| h == peer_handle) {
        return;
    }
    let (sk, pk) = generate_keypair();
    let card = sign_agent_card(&build_agent_card(peer_handle, &pk, None, None, None), &sk);
    add_agent_card_pin(trust, &card, None).unwrap();
    cards.push((peer_handle.to_string(), card));
}

fn apply(trust: &mut Trust, event: &Event, cards: &mut Vec<(String, Value)>) {
    match event {
        Event::AddPin(i) => {
            ensure_pinned(trust, PEERS[*i], cards);
        }
        Event::AttachOpCert(_) => {
            // RFC-001: op_cert attachment is a card-level change, not a
            // trust mutation. Modelled as a no-op against `trust`.
        }
        Event::AttachOrgCert(i) => {
            ensure_pinned(trust, PEERS[*i], cards);
            // promote_to_org_verified is only valid from UNTRUSTED;
            // above that it returns Err and we ignore.
            let _ = promote_to_org_verified(trust, PEERS[*i]);
        }
        Event::ReceivePairDropAck(i) => {
            ensure_pinned(trust, PEERS[*i], cards);
            // pair_drop_ack carries the peer's slot token but is not a
            // SAS confirmation. No trust mutation.
        }
        Event::SasConfirmed(i) => {
            ensure_pinned(trust, PEERS[*i], cards);
            let _ = promote_to_verified(trust, PEERS[*i]);
        }
    }
}

proptest! {
    /// Replay any sequence of identity-claim events and assert: every peer
    /// at VERIFIED MUST have had at least one SasConfirmed event for that
    /// peer in the trace. Equivalently — no path through the state machine
    /// elevates a peer to VERIFIED without crossing the SAS ceremony.
    #[test]
    fn ac2_verified_requires_sas(events in vec(event_strategy(), 0..40)) {
        let mut trust = empty_trust();
        let mut cards: Vec<(String, Value)> = Vec::new();
        let mut sas_seen: HashSet<usize> = HashSet::new();

        for event in &events {
            if let Event::SasConfirmed(i) = event {
                sas_seen.insert(*i);
            }
            apply(&mut trust, event, &mut cards);
        }

        for (i, peer) in PEERS.iter().enumerate() {
            let tier = get_tier(&trust, peer);
            if tier == "VERIFIED" {
                prop_assert!(
                    sas_seen.contains(&i),
                    "peer {peer} reached VERIFIED without any SasConfirmed event in trace {events:?}"
                );
            }
            // Tier must always be one of the known strings — guards
            // against silent string drift breaking the policy ladder.
            prop_assert!(
                ["UNTRUSTED", "ORG_VERIFIED", "VERIFIED", "ATTESTED", "TRUSTED"]
                    .contains(&tier.as_str()),
                "peer {peer} got unknown tier {tier:?}"
            );
        }
    }

    /// Bonus invariant: a trace with ZERO SasConfirmed events can never
    /// produce a single VERIFIED peer, regardless of how many org certs,
    /// op certs, pins, and pair-drop-acks flow through.
    #[test]
    fn ac2_no_sas_means_no_verified(
        non_sas_events in vec(
            prop_oneof![
                (0usize..PEERS.len()).prop_map(Event::AddPin),
                (0usize..PEERS.len()).prop_map(Event::AttachOpCert),
                (0usize..PEERS.len()).prop_map(Event::AttachOrgCert),
                (0usize..PEERS.len()).prop_map(Event::ReceivePairDropAck),
            ],
            0..60,
        )
    ) {
        let mut trust = empty_trust();
        let mut cards: Vec<(String, Value)> = Vec::new();

        for event in &non_sas_events {
            apply(&mut trust, event, &mut cards);
        }

        for peer in PEERS {
            let tier = get_tier(&trust, peer);
            prop_assert_ne!(
                tier.as_str(),
                "VERIFIED",
                "peer {} reached VERIFIED without any SAS event, via {:?}",
                peer,
                non_sas_events
            );
        }
    }
}
